---
title: "p8105_hw6_jr3755_rz2375"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(tidyverse)
library(httr)
library(jsonlite)
library(tidytext)
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 
```

Column {data-width=600}
-----------------------------------------------------------------------

### Barchart: Cuisine types

```{r}
nyc_inspections %>%
  distinct(camis, cuisine_description) %>%
  count(cuisine_description) %>% 
  mutate(cuisine_type = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_type, y = ~n, color = ~cuisine_description, type = "bar")  

boro = nyc_inspections %>% distinct(boro) %>% pull()
selectInput("boro_choice", label = h3("Select boro"),
            choices = boro, selected = "Manhattan")
renderPlotly({
  nyc_inspections %>%
  distinct(camis, cuisine_description) %>%
  filter(boro == input$boro_choice) %>%
  count(cuisine_description) %>% 
  mutate(cuisine_type = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_type, y = ~n, color = ~cuisine_description, type = "bar")
})
```

Column {data-width=400}
-----------------------------------------------------------------------

### Scatterplot: Word counts and Score

```{r}
nyc_inspections <- nyc_inspections %>% 
  mutate(inspection_num = row_number(), score = as.numeric(score))

inspection_words = nyc_inspections %>% 
  unnest_tokens(word, violation_description) %>% 
  group_by(inspection_num) %>% 
  mutate()

data(stop_words)
inspection_words = 
  anti_join(inspection_words, stop_words)

bing_sentiments = get_sentiments("bing")

inspection_sentiments = inspection_words %>% 
  inner_join(., bing_sentiments) %>% 
  count(inspection_num, sentiment) %>% 
  spread(sentiment, n, fill = 0)

inspection_sentiments = 
  right_join(nyc_inspections, inspection_sentiments, 
             by = "inspection_num")

scatter_plot <- inspection_sentiments %>% 
  ggplot(aes(x = positive, y = score)) +
  geom_point()
```

```{r}
nyc_inspections_maxannualgrade = 
  nyc_inspections %>%
  filter(!is.na(grade)) %>%
  distinct(camis, grade_date, grade) %>%
  separate(grade_date, into = c("grade_year", "remove"), sep = "-") %>%
  select(camis, grade_year, grade) %>%
  distinct(camis, grade_year, grade) %>%
  arrange(camis, grade_year, grade) %>%
  group_by(camis, grade_year) %>%
  mutate(grade = replace(grade, grade == "A", "5"),
         grade = replace(grade, grade == "B", "4"),
         grade = replace(grade, grade == "C", "3"),
         grade = replace(grade, grade == "Z", "2"),
         grade = replace(grade, grade == "P", "1"),
         grade = replace(grade, grade == "Not Yet Graded", "0")) %>%
  group_by(camis, grade_year) %>%
  mutate(grade = as.numeric(grade),
         max_grade = max(grade)) %>%
  mutate(max_grade = replace(max_grade, max_grade == "5", "A"),
         max_grade = replace(max_grade, max_grade == "4", "B"),
         max_grade = replace(max_grade, max_grade == "3", "C"),
         max_grade = replace(max_grade, max_grade == "2", "Z"),
         max_grade = replace(max_grade, max_grade == "1", "P"),
         max_grade = replace(max_grade, max_grade == "0", "Not Yet Graded")) %>%
  select(camis, grade_year, max_grade) %>%
  distinct(camis, grade_year, max_grade)

nyc_inspections_namencamis = 
  nyc_inspections %>%
  distinct(camis, dba)
  
nyc_inspections_annualgrade = 
  left_join(nyc_inspections_maxannualgrade, nyc_inspections_namencamis, key = "camis") %>%
  rename(restaurant_name = dba)

speghetti_plot_nyc_restaurant =
  nyc_inspections_annualgrade %>%
  ggplot(aes(x = grade_year, y = max_grade, color = camis)) +
  geom_point() +
  geom_path()

ggplotly(speghetti_plot_nyc_restaurant)
```

### Boxplot: Scores and grades

```{r}
boxplot <- nyc_inspections %>% 
  filter(!is.na(grade)) %>% 
  mutate(grade = as.factor(grade), score = as.numeric(score)) %>% 
  ggplot(aes(x = grade, y = score, color = grade)) + 
  geom_boxplot() +
  labs(title = "Boxplot for scores of different grades from inspections")
ggplotly(boxplot)
```
